weston:
  replicaCount: 1
  image:
    tag: latest
    pullPolicy: IfNotPresent
  securityContext:
    privileged: false
    allowPrivilegeEscalation: false
    runAsUser: 101
    runAsGroup: 101
    runAsNonRoot: true
  ingress:
    enabled: true
    hostName: weston-dev.awells.dev.actiandatacloud.com
    annotations:
      kubernetes.io/ingress.class: nginx
