haylen:
  replicaCount: 1
  securityContext:
    privileged: false
    allowPrivilegeEscalation: false
    runAsUser: 101
    runAsGroup: 101
    runAsNonRoot: true
    readOnlyRootFilesystem: false

  ingress:
    enabled: true
    hostName: haylen-dev.awells.dev.actiandatacloud.com
    annotations:
      kubernetes.io/ingress.class: nginx
