apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aw-es-prod-alien
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/auswells/engineering-summit-argocd.git
    targetRevision: HEAD
    path: environments/aw-es-prod/services/alien
    helm:
      releaseName: alien
      valueFiles:
        - values.yaml
  destination:
    name: aw-es-prod
    namespace: alien
  syncPolicy:
#    automated: {}
    syncOptions:
      - CreateNamespace=true
