ingress-nginx:
  controller:
    replicaCount: 2
    service:
      annotations:
        "service.beta.kubernetes.io/aws-load-balancer-proxy-protocol": '*'
      type: LoadBalancer
    extraArgs:
      default-ssl-certificate: ingress-nginx/star-cert
      enable-ssl-passthrough: ""
