external-dns:
  provider: aws
  aws:
    zoneType: "public"
  replicas: 1
  policy: sync
  registry: "txt"
  env:
    - name: AWS_ACCESS_KEY_ID
      valueFrom:
        secretKeyRef:
          name: aws-route53
          key: AWS_ACCESS_KEY_ID
    - name: AWS_SECRET_ACCESS_KEY
      valueFrom:
        secretKeyRef:
          name: aws-route53
          key: AWS_SECRET_ACCESS_KEY
