external-dns:
  provider: aws
  aws:
    zoneType: "public"
    credentials:
      secretName: aws-route53
  replicas: 1
  policy: sync
  registry: "txt"
  txtOwnerId: "aw-es-dev"
  zoneIdFilters:
    - Z3KI28UGUAVGZG
