apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aw-es-dev-weston
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/auswells/engineering-summit-argocd.git
    targetRevision: HEAD
    path: environments/aw-es-dev/services/weston
    helm:
      releaseName: weston
      valueFiles:
        values.yaml
  destination:
    server: aw-es-dev
    namespace: weston
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
