apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: star-cert
spec:
  refreshInterval: 1h           # rate SecretManager pulls GCPSM
  secretStoreRef:
    kind: ClusterSecretStore
    name: gcpsm                 # name of the SecretStore (or kind specified)
  target:
    name: star-cert             # name of the k8s Secret to be created
    creationPolicy: Owner
    # Specify a blueprint for the resulting Kind=Secret
    template:
      type: kubernetes.io/tls

      # Use inline templates to construct your desired config file that contains your secret
      data:
        tls.crt: {{` "{{ .tlscrt }}" `}}
        tls.key: {{` "{{ .tlskey }}" `}}

  data:
    - secretKey: tlscrt
      remoteRef:
        key: aw-star-cert
        property: tls.crt
    - secretKey: tlskey
      remoteRef:
        key: aw-star-cert
        property: tls.key
